### ISSUE TITLE
Prefer local CSS over Remote 

### ISSUE THREAD

**Issue by anoop-b** [claudiodangelis/qrcp#127]
I noticed that CSS [file](https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css) is fetched remotely, 
- Could this be stored locally maybe as a local file or as a variable? 
- Can cause issues when the devices isn't directly connected to the internet.

**Comment by claudiodangelis** [comment]
That would make sense, yes.

We could have it inline with something like
```css
<style>
/*!
 * Bootstrap v3.3.7 (http://getbootstrap.com)
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 *//*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}...
</style>
```
