### ISSUE TITLE
[Feature Request]: Switching file type for Windows releases

### ISSUE THREAD

**Issue by Dragon1573** [claudiodangelis/qrcp#352]
### For what?

- [ ] I have found a bug
- [x] I want to request a feature
- [ ] I have a question
- [ ] Other

> [!IMPORTANT]
> 
> This is a continuing discussion of previously closed issue. Also there's an external issue which related to this.
>
> - Related #288 
> - Related microsoft/winget-pkgs#30362
 
### Build environment

> [!NOTE]
> 
> I'm new to Golang and try building your project in an isolated _Windows Sandbox_ instance.
>
> Following outputs comes from the instance. There's NO Golang build environment installed on my host device.

- Golang version: `go version go1.23.4 windows/amd64`
- My `GOPATH` is set to: `C:\Users\WDAGUtilityAccount\go`

> [!NOTE]
> 
> The _Windows Sandbox_ instance is launched via PowerShell script [`Tools/SandboxTest.ps1`](https://github.com/microsoft/winget-pkgs/blob/master/Tools/SandboxTest.ps1). [`GoLang.Go`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/GoLang/Go/1.23.4) and [`Git.Git`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Git/Git/2.47.1) are both installed via [`winget.exe`](https://github.com/microsoft/winget-cli/). The `$env:GOPATH` is automatically configured by [_Golang Installer_](https://go.dev/dl/go1.23.4.windows-amd64.msi). I haven't configured it manually.

### Description

In previous discussion, there's a community contributor who wants to submit this package to `microsoft/winget-pkgs` repository. But the current release archive type `*.tar.gz` is not supported by `winget.exe` at the moment. Hence it breaks him/her enthusiasm.

According to [your comment](https://github.com/claudiodangelis/qrcp/issues/288#issuecomment-1850878648), this project uses _Go Releaser_. After [investigating it](https://goreleaser.com/customization/archive/#archives), I find it's possible to switch archives format from `*.tar.gz` to `*.zip` for Windows only (I see many projects uses ZIP as archive on Windows, other archive types are rarely seen), by adding following configurations to `release` section of `.goreleaser.yml`.

```yaml
# .goreleaser.yml

release:
  - # Can be used to change the archive formats for specific GOOSs.
    # Most common use case is to archive as zip on Windows.
    format_overrides:
      - # Which GOOS to override the format for.
        goos: windows

        # The format to use for the given GOOS.
        #
        # Valid options are `tar.gz`, `tgz`, `tar.xz`, `txz`, tar`, `gz`, `zip`, `binary`, and `none`.
        format: zip
```

Since [_WinGet manifest version `v1.9.0`_](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.9.0/README.md), it provides [enhanced support](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.9.0/installer.md#fields) of portable executables in ZIP archives. We can set `ArchiveBinariesDependOnPath: true` for those portable executables in ZIP archives. I think there's no more problems submitting this package to WinGet. ❤️
